language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pylint
before_script:
  - pylint --version
script:
  - pylint *.py --errors-only

notifications:
  email:
    on_success: never
    on_failure: change